### ISSUE TITLE
KeyError: 'EncoderDecoder_Distill is not in the models registry'

### ISSUE THREAD

**Issue by SingyooW** [xzz777/SCTNet#21]
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 201, in main
    model = build_segmentor(
  File "F:\anaconda3\envs\SCTNet\lib\site-packages\mmseg\models\builder.py", line 48, in build_segmentor
    return SEGMENTORS.build(
  File "F:\anaconda3\envs\SCTNet\lib\site-packages\mmcv\utils\registry.py", line 215, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "F:\anaconda3\envs\SCTNet\lib\site-packages\mmcv\cnn\builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "F:\anaconda3\envs\SCTNet\lib\site-packages\mmcv\utils\registry.py", line 44, in build_from_cfg
    raise KeyError(
KeyError: 'EncoderDecoder_Distill is not in the models registry'
(SCTNet) PS F:\20240128GDJ\DL_image_processing\SCTNet-master\tools>

**Comment by ZJDATY** [comment]
我有同样的问题

**Comment by ZJDATY** [comment]
https://github.com/xzz777/SCTNet/issues/18

**Comment by SingyooW** [comment]
> #18
thankyou

**Comment by bluebirdin** [comment]
I  also got this problem.

**Comment by Julianwerfzzv** [comment]
我也是这个问题，怎么解决
